name       : kmailtransport
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kmailtransport-17.08.1.tar.xz : 48addcf7195ddefed01ce519c62baa07d9a6376319058c45da854719195b1de5
license    : LGPL-2.1
component  : desktop.library
summary    : Mail Transport Service.
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
