name       : kmailtransport
version    : 18.04.2
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kmailtransport-18.04.2.tar.xz : 124c1bfeaf26111423ac61485bdc580704e888030559c130bba9acd653c081fd
license    : LGPL-2.1
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ksmtp-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
