name       : kmailtransport
version    : 17.12.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kmailtransport-17.12.3.tar.xz : c09d049e3f0285b8809662ce2c76d2c4d1848abb0a8f956b13d105a3baf03e8c
license    : LGPL-2.1
component  : desktop.library
summary    : Mail Transport Service.
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ksmtp-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
