name       : kmailtransport
version    : 21.04.3
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/kmailtransport-21.04.3.tar.xz : 95b0d84d1f4b2fed2fbf643a858d375accb02ad732b71b88edc74f6a4416a88f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - akonadi-mime-devel
    - kcmutils-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kio-devel
    - ksmtp-devel
    - kwallet-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - devel :
        - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
