name       : kmailtransport
version    : 22.08.3
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kmailtransport-22.08.3.tar.xz : 3721e27e3f6fdf7f59f70600f3a267f32854856c1973494e76e5c1225aa0e987
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - akonadi-mime-devel
    - kcmutils-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kio-devel
    - ksmtp-devel
    - kwallet-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - devel :
        - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
