name       : kmailtransport
version    : 22.04.3
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kmailtransport-22.04.3.tar.xz : f7c379b502f7b7c9f0aa0a7c6955844590994e25b7a252491e3035402ce58f39
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - akonadi-mime-devel
    - kcmutils-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kio-devel
    - ksmtp-devel
    - kwallet-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - devel :
        - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
