name       : kmailtransport
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kmailtransport-17.08.3.tar.xz : 0153668ba8edbe5816276e68f13dd1de696ca4f1a7e27ca78903f462f5fede31
license    : LGPL-2.1
component  : desktop.library
summary    : Mail Transport Service.
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
