name       : kmailtransport
version    : 22.04.1
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/kmailtransport-22.04.1.tar.xz : 8f1dc26f0dad28e81bce0f8ade3d83c811841bdb56a9b982032b1a233725add2
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - akonadi-mime-devel
    - kcmutils-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kio-devel
    - ksmtp-devel
    - kwallet-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - devel :
        - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
