name       : kmailtransport
version    : 19.12.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/kmailtransport-19.12.0.tar.xz : ac5b2fde3c024a13fc70bfd5b58317c258804144c156312d4d3e91fd34e16c89
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcontacts-devel
    - kdoctools-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ksmtp-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
    - libkgapi-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
