name       : kmailtransport
version    : 18.12.1
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kmailtransport-18.12.1.tar.xz : 758bf8b05a37ca7caafec57b488fa1820e77bae17318ef2caa82c58288be6af9
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ksmtp-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
    - libkgapi-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
