name       : kmailtransport
version    : 17.12.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kmailtransport-17.12.2.tar.xz : 487290cf2b0a2a6334fb29229f9bd1a6e6d266f8fda0b23cba5c94bf83e139df
license    : LGPL-2.1
component  : desktop.library
summary    : Mail Transport Service.
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ksmtp-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
