name       : kmailtransport
version    : 21.04.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kmailtransport-21.04.1.tar.xz : 8610610b615631e2b6cc24032cdcbb54a8a1afa680f459554df80bacd63fe50d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - akonadi-mime-devel
    - kcmutils-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kio-devel
    - ksmtp-devel
    - kwallet-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - devel :
        - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
