name       : kmailtransport
version    : 18.04.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kmailtransport-18.04.0.tar.xz : 8e80336d718228b94e5ee41dc738957e4b95decfba12df45ae1fd39dfe635f88
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Mail Transport Service.
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ksmtp-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
