name       : kmailtransport
version    : 21.08.3
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kmailtransport-21.08.3.tar.xz : 1c32f02ebc8b07f0ecd9af36111bef8e53fd62f463f5cf4ae70501b25c8dc476
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - akonadi-mime-devel
    - kcmutils-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kio-devel
    - ksmtp-devel
    - kwallet-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - devel :
        - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
