name       : kmailtransport
version    : 20.04.1
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/kmailtransport-20.04.1.tar.xz : 75abe8cd02c628950906f979fe29aa23659afcd770e91442750ed3dfffa398eb
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcontacts-devel
    - kdoctools-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ksmtp-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkgapi-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
