name       : kmailtransport
version    : 21.08.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kmailtransport-21.08.0.tar.xz : 49816deaecef128c6b29d0807de925029fc48971a18e6c50954ccb76868332f6
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - akonadi-mime-devel
    - kcmutils-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kio-devel
    - ksmtp-devel
    - kwallet-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - devel :
        - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
