name       : kmailtransport
version    : 18.04.3
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kmailtransport-18.04.3.tar.xz : e27ff6d37dbc96cd3be36ce4867aa9cc9c54cfc6927485ca8b3d5775d0fbd52a
license    : LGPL-2.1
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ksmtp-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
