name       : kmailtransport
version    : 22.04.2
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/kmailtransport-22.04.2.tar.xz : 8bbb45c781c5635da13ec51b628997f4a39e97a4cb1ee6d31f2418762ebbbb68
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - akonadi-mime-devel
    - kcmutils-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kio-devel
    - ksmtp-devel
    - kwallet-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - devel :
        - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
