name       : kmailtransport
version    : 18.08.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kmailtransport-18.08.0.tar.xz : 085fa632b17e83e0f372491379ca269185ef4caaf2e3220d0c4e0efc2fd0dc35
license    : LGPL-2.1
component  : desktop.library
summary    : Mail Transport Service
description: |
    Mail Transport Service.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ksmtp-devel
    - ktextwidgets-devel
    - kwallet-devel
    - libboost-devel
    - libkgapi-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
